### ISSUE TITLE
[Feature request] Skip absolute path imports

### ISSUE THREAD

**Issue by pdesjardins90** [cfware/babel-plugin-bare-import-rewrite#10]
Currently, if I have a `/src/some-folder/my-component.js` file like that:

```javascript
import { html } from '@polymer/polymer/polymer-element.js'
import { MyProjectDependency } from '/src/my-project-dependency.js'
...
```

The URL rewrite transforms that to:

```javascript
import { html } from '/node_modules/@polymer/polymer/polymer-element.js'
import { MyProjectDependency } from '/src/my-project-dependency.js'
...
```

And it outputs the following warning: 
> Could not resolve '/src/my-project-dependency.js' in file '...../src/some-folder/my-component.js'.

---

Would it be possible to rewrite the absolute paths to relative paths like the `polymer-build` project does?

**Comment by coreyfarrell** [comment]
I could add an option `ignoreAbsolute: true` to short-circuit the process, entirely skip translation of any file that is already absolute.  Would that serve your needs?  Another thought would be `ignorePrefixes: ["/"]` that way any specific prefixes could be ignored.

I'm not sure how I would rewrite the absolute path to be relative.

Worth noting the intent of this plugin is to translate node.js import statements to work in the browser, `import { something } from '/src/somewhere.js';` would only work in node.js if that absolute path actually exists on the filesystem.

**Comment by pdesjardins90** [comment]
Yeah you're right for the relative rewrite, I don't think it belongs in this plugin after all.

For my use-case, just skipping absolute imports would be great. 

For `ignorePrefixes: [ '/', ... ]`, not sure why would someone use this option for something else than absolute paths? If you have another use case in mind go ahead, both would work on my end!

**Comment by coreyfarrell** [comment]
My thought is that someone could use `ignorePrefixes: ['/src']` and still get a warning on `import something from '/not-permitted-path/source.js';`

**Comment by pdesjardins90** [comment]
Yeah I see your point, the added optionality is probably better too

**Comment by pdesjardins90** [comment]
@coreyfarrell I just published another [plugin](https://github.com/pdesjardins90/babel-plugin-relativify-imports) to convert absolute paths to relative ones that will fit perfectly right after yours in the plugin chain. Your repo was a big inspiration for it and I added a link to it in the README, thanks for your help!

**Comment by coreyfarrell** [comment]
@pdesjardins90 nice.  I'd suggest configuring travis-ci to test under Windows (see the .travis.yml from this repo).  When I enabled Windows testing for this repo I found a couple of Windows specific bugs caused by the different path separators.
