### ISSUE TITLE
[Feature request] fail when import cannot be resolved

### ISSUE THREAD

**Issue by LarsDenBakker** [cfware/babel-plugin-bare-import-rewrite#13]
Currently when an import cannot be resolved an error is logged but compilation does not fail. This makes it hard to spot errors during development, as code will be broken but it's not very apparent why.

Especially if you are working in the browser, and not looking at the terminal, the message: `Failed to resolve module specifier "foo". Relative references must start with either "/", "./", or "../".` is not very helpful.

I suggest adding an option to allow failing when a module could not be resolved.

I can work on a PR for this.

**Comment by coreyfarrell** [comment]
That sounds good.  Could you make it do a babel exception like https://github.com/jamiebuilds/babel-handbook/blob/master/translations/en/plugin-handbook.md#-throwing-a-syntax-error (note I have not actually tested example code).

**Comment by LarsDenBakker** [comment]
Will do. Do you want it to be configurable? And if so what should be the default behavior?

**Comment by coreyfarrell** [comment]
Throwing by default would be semver-major but it feels right.  I heard something at some point about browsers eventually getting 'built-in' modules, I'm unsure how that will work or if they'll be in a namespace.  Lets make it configurable and maintain current behavior by default for now.

I can do a semver-major after it's determined if anything can be done with bower_components?
