### ISSUE TITLE
[Feature request] multiple module directories

### ISSUE THREAD

**Issue by LarsDenBakker** [cfware/babel-plugin-bare-import-rewrite#14]
At work we are migrating from bower to npm, where some dependencies will be in `bower_components` and others in `node_modules`.

Would you mind if we make `modulesDir` an array of component directories to search in? The polymer tools also allowed this.

I can work on a PR for this.

**Comment by coreyfarrell** [comment]
`modulesDir` isn't actually the local `node_modules` directory, it's the HTTP URL path.  So for example in my own builds I use `modulesDir: '/assets'` and node_modules itself isn't available to the web server (`./assets` has a copy of the stuff the web server is allowed to share).

Currently this plugin doesn't have an option for setting the local `node_modules` (or bower_components) directory used to resolve the path of the module to be loaded.  I'm not clear how this would work or if https://github.com/browserify/resolve#readme can even resolve paths in bower_components.  It has an options `moduleDirectory` but I don't know how well it'll work if that contains non-node modules.

For options on this plugin maybe `modulesDir` could accept a String or Object.  So:
```js
function normalizeModulesDir(modulesDir) {
  if (typeof modulesDir === 'string') {
    return { 'node_modules': modulesDir };
  }
  return modulesDir;
}
```

This way you could set modulesDir as:
```json
{
  "node_modules": "/node_modules",
  "bower_components": "/bower_components"
}
```
Where each key would be the local directory to search and the value would be the URL associated with that local directory.

**Comment by LarsDenBakker** [comment]
I think that should work. For the polymer tools I made the same PR (https://github.com/Polymer/tools/blob/master/packages/analyzer/src/javascript/resolve-specifier-node.ts#L51) I think they use browserify resolve too.
